/**
 * Harmony Earth Sensor Registry & Multi-Hazard Sensor Network
 * 
 * Based on the WMO Global Observing System (GOS), USGS, BMKG, PVMBG, BIG, NOAA,
 * and ESA Copernicus master Earth Observation taxonomy.
 * 
 * Divides Earth sensors into 10 Core Families and cleanly decouples
 * physical sensors from carrier platforms (Satellite, Drone, Buoy, Ground Station, etc.).
 */

export type SensorFamily =
  | 'ATMOSPHERE'
  | 'WEATHER'
  | 'OCEAN_HYDROLOGY'
  | 'SOLID_EARTH_SEISMIC'
  | 'VOLCANO'
  | 'LAND_TERRAIN'
  | 'REMOTE_SENSING'
  | 'GEODESY_GNSS_GRAVITY'
  | 'BIOSPHERE_ENVIRONMENT'
  | 'HUMAN_INFRASTRUCTURE';

export type SensorPlatform =
  | 'SATELLITE'
  | 'GROUND_STATION'
  | 'OCEAN_BUOY'
  | 'SEAFLOOR_CABLE'
  | 'BOREHOLE'
  | 'AIRCRAFT_DRONE'
  | 'MOBILE_VEHICLE'
  | 'INFRASTRUCTURE_MOUNTED';

export type DisasterCategory =
  | 'GEMPA'
  | 'TEKTONIK'
  | 'TSUNAMI'
  | 'GUNUNG_API'
  | 'BANJIR'
  | 'LONGSOR'
  | 'CUACA_EKSTREM'
  | 'KARHUTLA'
  | 'KEKERINGAN'
  | 'SUBSIDENCE';

export interface SensorFamilyMetadata {
  id: SensorFamily;
  code: string;
  name: string;
  description: string;
  iconName: string;
  colorHex: string;
  badgeBg: string;
  badgeText: string;
  primaryVariables: string[];
}

export const SENSOR_FAMILY_META: Record<SensorFamily, SensorFamilyMetadata> = {
  SOLID_EARTH_SEISMIC: {
    id: 'SOLID_EARTH_SEISMIC',
    code: '04',
    name: 'Gempa Bumi & Seismik',
    description: 'Pemantauan getaran litosfer, gelombang P/S, percepatan tanah (PGA), dan patahan sesar aktif.',
    iconName: 'Activity',
    colorHex: '#ef4444',
    badgeBg: 'bg-red-500/10 dark:bg-red-950/40',
    badgeText: 'text-red-600 dark:text-red-400 border-red-500/30',
    primaryVariables: ['PGA (gal)', 'Kecepatan Tanah (cm/s)', 'Magnitudo M', 'Kedalaman Hiposenter', 'Regangan Patahan'],
  },
  GEODESY_GNSS_GRAVITY: {
    id: 'GEODESY_GNSS_GRAVITY',
    code: '08',
    name: 'Tektonik, GNSS & Gravitasi',
    description: 'Pengukuran deformasi kerak bumi kontinu, laju pergerakan lempeng tektonik, dan anomali gravitasi massa air.',
    iconName: 'Compass',
    colorHex: '#8b5cf6',
    badgeBg: 'bg-purple-500/10 dark:bg-purple-950/40',
    badgeText: 'text-purple-600 dark:text-purple-400 border-purple-500/30',
    primaryVariables: ['Pergeseran Kerak (mm/tahun)', 'Azimuth Lempeng (°)', 'PWV Troposfer (mm)', 'Anomali Massa Gravitasi'],
  },
  VOLCANO: {
    id: 'VOLCANO',
    code: '05',
    name: 'Gunung Api & Magma',
    description: 'Multi-parameter pos pemantauan gunung api: gempa vulkanik, deformasi tiltmeter, emisi gas SO2, dan lahar.',
    iconName: 'Flame',
    colorHex: '#f97316',
    badgeBg: 'bg-amber-500/10 dark:bg-amber-950/40',
    badgeText: 'text-amber-600 dark:text-amber-400 border-amber-500/30',
    primaryVariables: ['Tilt Deformasi (µrad)', 'Fluks Gas SO2 (ton/hari)', 'Gempa Vulkanik (ev/hari)', 'Suhu Kubah Lava (°C)'],
  },
  OCEAN_HYDROLOGY: {
    id: 'OCEAN_HYDROLOGY',
    code: '03',
    name: 'Oseanografi & Tsunami',
    description: 'Sensor tekanan laut dalam (BPR), kabel bawah laut, tsunami buoy (DART), tide gauge pasang surut, dan debit sungai.',
    iconName: 'Waves',
    colorHex: '#0284c7',
    badgeBg: 'bg-sky-500/10 dark:bg-sky-950/40',
    badgeText: 'text-sky-600 dark:text-sky-400 border-sky-500/30',
    primaryVariables: ['Tekanan Dasar Laut (MPa)', 'Anomali Muka Air Laut (m)', 'Tinggi Gelombang (m)', 'Kecepatan Arus (m/s)'],
  },
  WEATHER: {
    id: 'WEATHER',
    code: '02',
    name: 'Radar Cuaca & Meteorologi',
    description: 'Radar cuaca Doppler C/S/X-band, stasiun cuaca otomatis (AWS), dan disdrometer ukuran butir hujan.',
    iconName: 'CloudRain',
    colorHex: '#10b981',
    badgeBg: 'bg-emerald-500/10 dark:bg-emerald-950/40',
    badgeText: 'text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    primaryVariables: ['Reflektivitas Radar (dBZ)', 'Curah Hujan (mm/jam)', 'Kecepatan Angin (knot)', 'Arah Angin (°)'],
  },
  ATMOSPHERE: {
    id: 'ATMOSPHERE',
    code: '01',
    name: 'Atmosfer & Upper-Air',
    description: 'Profil vertikal atmosfer radiosonde, lidar angin Doppler, detektor petir VLF/LF, dan radiasi matahari pyranometer.',
    iconName: 'CloudLightning',
    colorHex: '#06b6d4',
    badgeBg: 'bg-cyan-500/10 dark:bg-cyan-950/40',
    badgeText: 'text-cyan-600 dark:text-cyan-400 border-cyan-500/30',
    primaryVariables: ['Profil Vertikal Suhu (°C)', 'Tekanan Barometrik (hPa)', 'Deteksi Sambaran Petir', 'Radiasi Global (W/m²)'],
  },
  LAND_TERRAIN: {
    id: 'LAND_TERRAIN',
    code: '06',
    name: 'Gerakan Tanah & Longsor',
    description: 'Sistem peringatan dini lereng: inklinometer bawah permukaan, tensiometer air pori tanah, dan ekstensiometer retakan.',
    iconName: 'Mountain',
    colorHex: '#d97706',
    badgeBg: 'bg-yellow-500/10 dark:bg-yellow-950/40',
    badgeText: 'text-yellow-600 dark:text-yellow-400 border-yellow-500/30',
    primaryVariables: ['Kemiringan Lereng (derajat)', 'Tekanan Air Pori (kPa)', 'Kelembapan Volumetrik Tanah (%)', 'Laju Retakan (mm/hari)'],
  },
  REMOTE_SENSING: {
    id: 'REMOTE_SENSING',
    code: '07',
    name: 'Satelit Pengamatan Bumi',
    description: 'Satelit radar SAR tembus awan (Sentinel-1, ALOS), citra optik multispektral (Sentinel-2, Landsat), dan LiDAR (ICESat-2).',
    iconName: 'Satellite',
    colorHex: '#6366f1',
    badgeBg: 'bg-indigo-500/10 dark:bg-indigo-950/40',
    badgeText: 'text-indigo-600 dark:text-indigo-400 border-indigo-500/30',
    primaryVariables: ['Interferometri Deformasi InSAR (mm)', 'Indeks Vegetasi NDVI', 'Elevasi Kanopi & Es (m)', 'Tinggi Muka Air SWOT (m)'],
  },
  BIOSPHERE_ENVIRONMENT: {
    id: 'BIOSPHERE_ENVIRONMENT',
    code: '09',
    name: 'Lingkungan & Kualitas Udara',
    description: 'Sensor konsentrasi partikulat PM2.5/PM10, gas polutan troposfer (NO2, SO2, CO), dan deteksi hotspot karhutla satelit.',
    iconName: 'Leaf',
    colorHex: '#14b8a6',
    badgeBg: 'bg-teal-500/10 dark:bg-teal-950/40',
    badgeText: 'text-teal-600 dark:text-teal-400 border-teal-500/30',
    primaryVariables: ['Konsentrasi PM2.5 (µg/m³)', 'Kolom Troposfer NO2 (mol/m²)', 'FRP Daya Radiatif Api (MW)', 'Aerosol Optical Depth'],
  },
  HUMAN_INFRASTRUCTURE: {
    id: 'HUMAN_INFRASTRUCTURE',
    code: '10',
    name: 'Infrastruktur Sipil Kritis',
    description: 'Structural Health Monitoring (SHM) untuk jembatan bentang panjang, rembesan bendungan waduk, dan integritas jalan raya.',
    iconName: 'Building2',
    colorHex: '#64748b',
    badgeBg: 'bg-slate-500/10 dark:bg-slate-950/40',
    badgeText: 'text-slate-600 dark:text-slate-400 border-slate-500/30',
    primaryVariables: ['Akselerasi Getaran Struktur (g)', 'Tegangan Strain Gauge (µε)', 'Rembesan Tekanan Piezometer (bar)', 'Deformasi Kritis (mm)'],
  },
};

export interface EarthSensorNode {
  id: string;
  name: string;
  code: string;
  family: SensorFamily;
  subCategory: string;
  platform: SensorPlatform;
  provider: string;
  country: string;
  flag: string;
  lat: number;
  lng: number;
  altitudeM?: number;
  depthM?: number;
  status: 'ONLINE' | 'ACTIVE' | 'MAINTENANCE' | 'ALERT';
  samplingRate: string;
  primaryMeasurement: string;
  unit: string;
  currentValue: string | number;
  accuracy: string;
  coverage: string;
  disasterRelevance: DisasterCategory[];
  description: string;
  lastPing: string;
  telemetryType: string;
}

export interface MasterTaxonomyCategory {
  id: number;
  family: SensorFamily;
  title: string;
  description: string;
  primaryInstruments: string[];
  measuredPhysicalVariables: string[];
  representativePlatforms: string[];
  disastersAddressed: DisasterCategory[];
}

export const MASTER_SENSOR_TAXONOMY: MasterTaxonomyCategory[] = [
  {
    id: 1,
    family: 'ATMOSPHERE',
    title: 'Sensor Atmosfer & Cuaca Permukaan',
    description: 'Pengamatan elemen fisik dasar udara pada permukaan bumi meliputi termodinamika, tekanan, angin, dan radiasi.',
    primaryInstruments: ['Platinum Resistance Thermometer', 'Capacitive Humidity Sensor', 'MEMS Barometer', 'Ultrasonic 3D Anemometer', 'Tipping Bucket & Weighing Rain Gauge', 'Pyranometer', 'All-sky Camera', 'Optical Lightning Detector'],
    measuredPhysicalVariables: ['Suhu Udara (°C)', 'Kelembapan Relatif (%)', 'Tekanan Udara (hPa)', 'Vektor Angin (m/s)', 'Intensitas Hujan (mm/jam)', 'Radiasi Surya (W/m²)', 'Sambaran Petir'],
    representativePlatforms: ['AWS Ground Station', 'Stasiun Klimatologi BMKG', 'Menara Meteorologi Tower'],
    disastersAddressed: ['CUACA_EKSTREM', 'BANJIR', 'KEKERINGAN', 'KARHUTLA'],
  },
  {
    id: 2,
    family: 'ATMOSPHERE',
    title: 'Upper-Air & Atmosfer Vertikal',
    description: 'Profil struktur atmosfer vertikal dari permukaan hingga stratosfer (30 km) untuk pemodelan cuaca numerik (NWP).',
    primaryInstruments: ['GPS Radiosonde', 'Dropsonde', 'Rawinsonde', 'Wind Profiler Radar', 'Doppler Lidar', 'Microwave Atmospheric Sounder'],
    measuredPhysicalVariables: ['Profil Vertikal Suhu & Kelembapan', 'Geseran Angin Vertikal (Wind Shear)', 'Tinggi Lapisan Batas Tropopause', 'Indeks Ketidakstabilan CAPE'],
    representativePlatforms: ['Balon Radiosonde Cuaca', 'Pesawat Dropsonde', 'Stasiun Profiler Darat'],
    disastersAddressed: ['CUACA_EKSTREM', 'BANJIR'],
  },
  {
    id: 3,
    family: 'WEATHER',
    title: 'Radar Meteorologi',
    description: 'Radar gelombang mikro aktif mendeteksi presipitasi, pergerakan awan konvektif, dan siklon badai secara realtime.',
    primaryInstruments: ['Doppler Weather Radar', 'C-Band Polarimetric Radar', 'S-Band Radar', 'X-Band Phased-Array Radar'],
    measuredPhysicalVariables: ['Reflektivitas Radar Zh (dBZ)', 'Kecepatan Radial Doppler (m/s)', 'Differential Reflectivity Zdr', 'Estimasi Laju Hujan QPE (mm/jam)'],
    representativePlatforms: ['Stasiun Radar BMKG Darat', 'Mobile Radar Truck', 'Radar Kapal Maritim'],
    disastersAddressed: ['CUACA_EKSTREM', 'BANJIR', 'LONGSOR'],
  },
  {
    id: 4,
    family: 'REMOTE_SENSING',
    title: 'Satelit Optik / Multispektral',
    description: 'Pencitraan pantulan spektrum elektromagnetik bumi (VNIR, SWIR, TIR) untuk pemetaan vegetasi, tutupan lahan, dan kerusakan bencana.',
    primaryInstruments: ['Multispectral Instrument (MSI)', 'Operational Land Imager (OLI)', 'Advanced Baseline Imager (ABI)', 'Advanced Himawari Imager (AHI)'],
    measuredPhysicalVariables: ['Reflektansi Spektral Permukaan', 'Temperatur Kecerahan Puncak Awan', 'Luas Genangan Banjir Optik', 'Indeks Kerusakan Vegetasi (NBR/NDVI)'],
    representativePlatforms: ['Sentinel-2 (ESA)', 'Landsat-8/9 (USGS/NASA)', 'Himawari-9 (JMA)', 'GOES-16/18 (NOAA)'],
    disastersAddressed: ['BANJIR', 'KARHUTLA', 'KEKERINGAN', 'LONGSOR'],
  },
  {
    id: 5,
    family: 'REMOTE_SENSING',
    title: 'Satelit Radar / SAR (Synthetic Aperture Radar)',
    description: 'Pengamatan radar aktif tembus awan siang/malam, memungkinkan deteksi deformasi skala milimeter melalui teknik InSAR.',
    primaryInstruments: ['C-Band SAR (Sentinel-1)', 'L-Band SAR (ALOS-2/4 PALSAR)', 'X-Band SAR (TerraSAR-X)', 'S/L Dual-Band SAR (NISAR)'],
    measuredPhysicalVariables: ['Koefisien Hamburan Balik Radar Sigma0 (dB)', 'Fase Interferometri (Interferogram InSAR)', 'Pergeseran Permukaan Tanah (mm)', 'Batas Air Genangan Tembus Awan'],
    representativePlatforms: ['Sentinel-1 (Copernicus)', 'ALOS-2 PALSAR (JAXA)', 'NISAR (NASA/ISRO)', 'TerraSAR-X (DLR)'],
    disastersAddressed: ['GEMPA', 'TEKTONIK', 'BANJIR', 'LONGSOR', 'GUNUNG_API', 'SUBSIDENCE'],
  },
  {
    id: 6,
    family: 'REMOTE_SENSING',
    title: 'LiDAR (Light Detection and Ranging)',
    description: 'Sensor pulsa laser presisi untuk menghasilkan model elevasi digital (DEM/DSM) 3D, struktur kanopi hutan, dan garis pantai.',
    primaryInstruments: ['Airborne Topographic LiDAR', 'Bathymetric Green Laser LiDAR', 'ATLAS Photon-Counting Laser (ICESat-2)', 'GEDI Spaceborne Canopy LiDAR'],
    measuredPhysicalVariables: ['Elevasi Titik 3D Titik Tanah Bare-Earth (m)', 'Tinggi Kanopi Hutan (m)', 'Kedalaman Batimetri Dangkal (m)', 'Profil Lereng Curam'],
    representativePlatforms: ['Pesawat Airborne LiDAR', 'Drone UAV Survey', 'ICESat-2 (NASA)', 'Stasiun Terestrial LiDAR'],
    disastersAddressed: ['LONGSOR', 'BANJIR', 'TSUNAMI', 'SUBSIDENCE'],
  },
  {
    id: 7,
    family: 'OCEAN_HYDROLOGY',
    title: 'Altimeter Satelit & Radar Muka Air',
    description: 'Pengukuran jarak vertikal dari sensor ke permukaan air laut, danau, dan sungai besar untuk mengamati kenaikan muka air global.',
    primaryInstruments: ['KaRIn Ka-Band Radar Interferometer (SWOT)', 'Nadir Radar Altimeter (Poseidon-4)', 'Laser Altimeter', 'Radar Water-Level Gauge'],
    measuredPhysicalVariables: ['Ketinggian Muka Air Sungai & Danau (m)', 'Sea-Surface Height Anomaly (cm)', 'Signifikan Tinggi Gelombang Laut (m)'],
    representativePlatforms: ['SWOT Satellite (NASA/CNES)', 'Sentinel-6 Michael Freilich', 'Stasiun Altimeter Jembatan Sungai'],
    disastersAddressed: ['BANJIR', 'TSUNAMI'],
  },
  {
    id: 8,
    family: 'OCEAN_HYDROLOGY',
    title: 'Sensor Kelautan & Oseanografi Fisika-Kimia',
    description: 'Rangkaian sensor in-situ mengukur massa air laut, sirkulasi arus, pasang surut, salinitas, dan suhu permukaan laut.',
    primaryInstruments: ['Conductivity-Temperature-Depth (CTD)', 'Acoustic Doppler Current Profiler (ADCP)', 'Accelerometer Wave Buoy', 'Sea Surface Infrared Radiometer'],
    measuredPhysicalVariables: ['Suhu Air Laut SST (°C)', 'Salinitas Praktis (PSU)', 'Vektor Arus Bawah Laut 3D (m/s)', 'Spektrum Gelombang Laut (m)'],
    representativePlatforms: ['Argo Profiling Float', 'Moored Oceanic Buoy', 'Pelampung Hanyut Drifter', 'Kapal Riset Riset Kelautan'],
    disastersAddressed: ['TSUNAMI', 'CUACA_EKSTREM'],
  },
  {
    id: 9,
    family: 'OCEAN_HYDROLOGY',
    title: 'Sensor Hidrologi Sungai & Air Tanah',
    description: 'Pemantauan fluktuasi level debit sungai dan akuifer air tanah untuk peringatan dini banjir luapan DAS.',
    primaryInstruments: ['Radar Water-Level Sensor', 'Ultrasonic River Gauge', 'Bubbler Pressure Transducer', 'Piezometer Akuifer', 'River Velocity Radar'],
    measuredPhysicalVariables: ['Tinggi Muka Air Sungai TMA (m)', 'Debit Aliran Q (m³/s)', 'Level Muka Air Tanah (m di bawah muka tanah)', 'Kecepatan Aliran Permukaan (m/s)'],
    representativePlatforms: ['Pos Duga Air (PDA) BBWS', 'Piezometer Sumur Pantau', 'Stasiun Pemantau Sungai Otomatis'],
    disastersAddressed: ['BANJIR', 'KEKERINGAN', 'SUBSIDENCE'],
  },
  {
    id: 10,
    family: 'LAND_TERRAIN',
    title: 'Sensor Sifat Fisik Tanah & Zona Tak Jenuh',
    description: 'Sensor kelembapan, tegangan air pori, dan konduktivitas listrik tanah untuk analisis kestabilan lereng dan kekeringan agrikultur.',
    primaryInstruments: ['Time Domain Reflectometry (TDR) Moisture Sensor', 'Tensiometer Tegangan Air Pori', 'Soil Electrical Conductivity (EC) Sensor', 'Dielectric Permittivity Sensor'],
    measuredPhysicalVariables: ['Kadar Air Volumetrik Tanah VWC (%)', 'Matric Suction Tegangan Pori (kPa)', 'Suhu Tanah Kedalaman 20-100 cm (°C)', 'Salinitas Tanah (dS/m)'],
    representativePlatforms: ['Stasiun Agrometeorologi', 'Borehole Lereng Rawan Longsor', 'Jaringan SMAP In-Situ Validation'],
    disastersAddressed: ['LONGSOR', 'KEKERINGAN', 'BANJIR'],
  },
  {
    id: 11,
    family: 'SOLID_EARTH_SEISMIC',
    title: 'Sensor Gempa Bumi & Seismologi Litosfer',
    description: 'Jaringan instrumen pengukur getaran mekanis tanah, kecepatan dan percepatan gelombang seismik dari rekahan batuan bawah permukaan.',
    primaryInstruments: ['Broadband Seismometer (120s - 50Hz)', 'Short-Period Seismometer', 'Strong-Motion Force-Balance Accelerometer', 'Ocean-Bottom Seismometer (OBS)', 'Borehole Geophone'],
    measuredPhysicalVariables: ['Percepatan Puncak Tanah PGA (gal / cm/s²)', 'Spektrum Kecepatan Gelombang P & S', 'Magnitudo Momen Mw', 'Waktu Tiba Gelombang Seismik (detik)'],
    representativePlatforms: ['Stasiun Seismik InaTEWS BMKG', 'USGS Global Seismographic Network (GSN)', 'Observatorium Bawah Laut OBS', 'Borehole Deep Well'],
    disastersAddressed: ['GEMPA', 'TSUNAMI', 'GUNUNG_API'],
  },
  {
    id: 12,
    family: 'GEODESY_GNSS_GRAVITY',
    title: 'Geodesi Satelit GNSS / GPS Kontinu',
    description: 'Jaringan referensi geodetik kontinu berefisiensi fraksi milimeter untuk menghitung vektor pergeseran lempeng tektonik dan akumulasi regangan.',
    primaryInstruments: ['Multi-GNSS Geodetic Receiver (GPS/Galileo/GLONASS/BeiDou)', 'Choke-Ring Multi-Path Resistant Antenna', 'CORS Continuous Station Receiver'],
    measuredPhysicalVariables: ['Koordinat 3D Presisi Tinggi (X, Y, Z)', 'Laju Deformasi Lempeng (mm/tahun)', 'Precipitable Water Vapor PWV (mm)', 'Total Electron Content TEC Ionosfer'],
    representativePlatforms: ['Stasiun InaCORS Badan Informasi Geospasial (BIG)', 'IGS Global Geodetic Network', 'Monumen Geodetik Sesar Aktif'],
    disastersAddressed: ['TEKTONIK', 'GEMPA', 'GUNUNG_API', 'SUBSIDENCE'],
  },
  {
    id: 13,
    family: 'GEODESY_GNSS_GRAVITY',
    title: 'Gravimetri Bumi & Geodinamika Massa',
    description: 'Sensor percepatan gravitasi bumi untuk memantau perubahan redistribusi massa air tanah, es kutub, dan dinamika magma.',
    primaryInstruments: ['Superconducting Relative Gravimeter', 'Free-Fall Absolute Gravimeter (FG5-X)', 'K-Band Intersatellite Microwave Ranging (GRACE-FO)', 'Laser Ranging Interferometer'],
    measuredPhysicalVariables: ['Percepatan Gravitasi Mutlak g (µGal)', 'Anomali Massa Air Tersimpan EWH (cm)', 'Perubahan Densitas Bawah Permukaan'],
    representativePlatforms: ['GRACE-FO Twin Satellite (NASA/GFZ)', 'Stasiun Gravitasi Permanen BIG', 'Airborne Gravimetry Survey'],
    disastersAddressed: ['KEKERINGAN', 'TEKTONIK', 'GUNUNG_API', 'SUBSIDENCE'],
  },
  {
    id: 14,
    family: 'GEODESY_GNSS_GRAVITY',
    title: 'Geomagnetik & Medan Magnet Bumi',
    description: 'Pengukuran komponen vektor dan skalar medan magnet bumi untuk pemetaan geologi, eksplorasi tektonik, dan badai antariksa geomagnetik.',
    primaryInstruments: ['Fluxgate Triaxial Magnetometer', 'Overhauser High-Precision Magnetometer', 'Proton Precession Magnetometer', 'Cesium Optical Pumping Magnetometer'],
    measuredPhysicalVariables: ['Intensitas Medan Magnet Total F (nT)', 'Komponen Horizontal H & Vertikal Z (nT)', 'Deklinasi & Inklinasi Magnetik (°)'],
    representativePlatforms: ['Observatorium Geomagnet BMKG', 'Satelit ESA Swarm', 'Pesawat Aeromagnetik'],
    disastersAddressed: ['TEKTONIK', 'CUACA_EKSTREM'],
  },
  {
    id: 15,
    family: 'VOLCANO',
    title: 'Instrumentasi Multi-Parameter Gunung Api',
    description: 'Sub-sistem pemantauan gunung api aktif terpadu menggabungkan seismisitas magmatik, deformasi tubuh gunung, fluks gas, dan visual termal.',
    primaryInstruments: ['Borehole Quartz Tiltmeter', 'Differential Optical Absorption Spectrometer (DOAS / Mini-DOAS)', 'Multi-GAS Analyser (SO2/CO2/H2S)', 'Infrasound Microphone Array', 'Thermal Infrared Radiometric Camera', 'Acoustic Lahar Flow Sensor (AFM)'],
    measuredPhysicalVariables: ['Defleksi Inflasi/Deflasi Tilt (mikroradian)', 'Fluks Emisi Gas SO2 (ton/hari)', 'Rasio Gas CO2/SO2', 'Amplitudo Frekuensi Rendah Infrasound (Pa)', 'Suhu Titik Panas Kubah Kawah (°C)'],
    representativePlatforms: ['Pos Pengamatan Gunung Api PVMBG Magma', 'Stasiun Puncak Telemetri Tenaga Surya', 'Pesawat Drone Sampling Kawah'],
    disastersAddressed: ['GUNUNG_API', 'GEMPA', 'LONGSOR'],
  },
  {
    id: 16,
    family: 'LAND_TERRAIN',
    title: 'Sistem Monitoring Gerakan Tanah / Longsor Terpadu',
    description: 'Kombinasi sensor geoteknik dan hidrometeorologi lereng untuk menentukan ambang batas keruntuhan massa tanah.',
    primaryInstruments: ['Borehole Inclinometer Array', 'Wire Extensometer', 'Piezometer Vibrating Wire', 'Pore Water Pressure Gauge', 'Ground Geophone Tremor'],
    measuredPhysicalVariables: ['Pergeseran Horisontal Bidang Gelincir (mm)', 'Laju Ekstensi Retakan (mm/jam)', 'Tekanan Air Pori Hidrolik (kPa)', 'Getaran Mikroseismik Awal Runtuhan'],
    representativePlatforms: ['Lereng Kritis Jalan Tol / Kereta Api', 'Zona Permukiman Rawan Longsor PVMBG', 'Lereng Pertambangan Tebing'],
    disastersAddressed: ['LONGSOR', 'BANJIR'],
  },
  {
    id: 17,
    family: 'OCEAN_HYDROLOGY',
    title: 'Sistem Deteksi Tsunami Laut Dalam & Pesisir',
    description: 'Sensor tsunameter bawah laut dan stasiun pasang surut pesisir berkecepatan tinggi untuk konfirmasi gelombang tsunami realtime.',
    primaryInstruments: ['Quartz Bottom Pressure Recorder (BPR)', 'DART Moored Ocean Buoy', 'Submarine Optical Fiber Seafloor Tsunameter (InaCBT / S-net / DONET)', 'Radar Tide Gauge'],
    measuredPhysicalVariables: ['Fluktuasi Tekanan Kolom Air Laut (milibar)', 'Anomali Ketinggian Gelombang Tsunami (cm)', 'Waktu Tempuh Perambatan Tsunami (menit)'],
    representativePlatforms: ['Kabel Bawah Laut S-net (Jepang)', 'Kabel DONET Nankai', 'NOAA DART Array Buoy', 'InaTEWS Tide Gauge BIG'],
    disastersAddressed: ['TSUNAMI', 'GEMPA'],
  },
  {
    id: 18,
    family: 'BIOSPHERE_ENVIRONMENT',
    title: 'Deteksi Kebakaran Hutan & Lahan (Karhutla)',
    description: 'Sensor satelit termal inframerah spektrum SWIR/MWIR dan stasiun mikrometeorologi untuk identifikasi titik panas dan sebaran asap.',
    primaryInstruments: ['MODIS Thermal Anomaly Detector', 'VIIRS Active Fire Sensor (375 m)', 'Geostationary Fire Radiative Power (FRP) Radiometer', 'Ground PM2.5 Optical Smoke Sensor'],
    measuredPhysicalVariables: ['Daya Radiatif Kebakaran FRP (MW)', 'Suhu Kecerahan Hotspot 4µm (Kelvin)', 'Kerapatan Sebaran Asap Optik AOD', 'Tingkat Kelembapan Bahan Bakar Gambut'],
    representativePlatforms: ['Satelit Suomi-NPP & NOAA-20', 'Satelit Terra & Aqua (NASA FIRMS)', 'Menara Pantau Karhutla KLHK'],
    disastersAddressed: ['KARHUTLA', 'KEKERINGAN'],
  },
  {
    id: 19,
    family: 'REMOTE_SENSING',
    title: 'Deformasi Permukaan Tanah & Amblesan (Subsidence)',
    description: 'Pemantauan laju amblesan tanah perkotaan pesisir dan wilayah ekstraksi air tanah menggunakan kombinasi InSAR, GNSS, dan leveling.',
    primaryInstruments: ['Synthetic Aperture Radar Interferometry (InSAR)', 'Continuous Geodetic GNSS Station', 'High-Precision Digital Leveling', 'Extensometer Lapisan Lempung'],
    measuredPhysicalVariables: ['Laju Penurunan Tanah Vertikal (cm/tahun)', 'Deformasi Spasial Bidang Pesisir', 'Tingkat Pemadatan Lapisan Akuifer'],
    representativePlatforms: ['Sentinel-1 Copernicus Radar', 'Stasiun GNSS Geodesi Pantau Pesisir', 'Borehole Extensometer BIG'],
    disastersAddressed: ['SUBSIDENCE', 'BANJIR', 'TEKTONIK'],
  },
  {
    id: 20,
    family: 'BIOSPHERE_ENVIRONMENT',
    title: 'Sensor Kualitas Udara & Polusi Atmosfer',
    description: 'Spektrometer satelit dan stasiun darat mengukur konsentrasi partikel debu halus dan gas berbahaya bagi kesehatan manusia.',
    primaryInstruments: ['TROPOMI Atmospheric Spectrometer (Sentinel-5P)', 'Beta Attenuation Monitor (BAM PM2.5)', 'Laser Optical Particle Counter', 'Chemiluminescence Gas Analyzer (NO2/SO2/O3)'],
    measuredPhysicalVariables: ['Konsentrasi Partikulat PM2.5 & PM10 (µg/m³)', 'Kolom Troposfer NO2 (mol/m²)', 'Konsentrasi Gas Ozon Permukaan O3 (ppb)', 'Aerosol Index Abu Vulkanik'],
    representativePlatforms: ['Sentinel-5P Satellite (Copernicus)', 'Stasiun Air Quality Monitoring System (AQMS) KLHK/BMKG', 'Sensor Komunitas Berjejaring'],
    disastersAddressed: ['CUACA_EKSTREM', 'GUNUNG_API', 'KARHUTLA'],
  },
];

export const GLOBAL_EARTH_SENSOR_NETWORK: EarthSensorNode[] = [
  // ================= 1. SOLID EARTH / SEISMIC =================
  {
    id: 'seismo_tji_tretes',
    name: 'Sensor Seismometer InaTEWS Tretes (TJI)',
    code: 'BMKG-TJI',
    family: 'SOLID_EARTH_SEISMIC',
    subCategory: 'Broadband Seismometer & Akselerometer',
    platform: 'GROUND_STATION',
    provider: 'BMKG InaTEWS',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -7.7021,
    lng: 112.6284,
    altitudeM: 840,
    status: 'ONLINE',
    samplingRate: '100 Hz Realtime',
    primaryMeasurement: 'Percepatan Tanah 3-Komponen (PGA) & Gelombang P/S',
    unit: 'gal (cm/s²)',
    currentValue: '0.008 gal',
    accuracy: '±0.0001 gal (24-bit ADC)',
    coverage: 'Radius 150 km Jawa Timur',
    disasterRelevance: ['GEMPA', 'TSUNAMI'],
    description: 'Stasiun seismik broadband referensi tinggi di lereng Gunung Welirang-Arjuno untuk peringatan dini gempa bumi Jawa Timur dan palung selatan.',
    lastPing: 'Live Realtime (< 1s)',
    telemetryType: 'VSAT IP & Fiber Optic Dedicated',
  },
  {
    id: 'seismo_lem_lombok',
    name: 'Sensor Seismometer Lembar (LEM)',
    code: 'BMKG-LEM',
    family: 'SOLID_EARTH_SEISMIC',
    subCategory: 'Broadband Seismometer',
    platform: 'GROUND_STATION',
    provider: 'BMKG InaTEWS',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -8.7231,
    lng: 116.0745,
    altitudeM: 65,
    status: 'ONLINE',
    samplingRate: '100 Hz Realtime',
    primaryMeasurement: 'Kecepatan Partikel Gelombang Seismik',
    unit: 'µm/s',
    currentValue: '0.42 µm/s',
    accuracy: '±0.001 µm/s',
    coverage: 'Busur Sunda-Banda & Sesar Naik Flores',
    disasterRelevance: ['GEMPA', 'TSUNAMI'],
    description: 'Pemantauan seismisitas zona subduksi lempeng selatan Lombok dan sesar naik busur belakang (Flores Back-Arc Thrust).',
    lastPing: 'Live Realtime (< 1s)',
    telemetryType: 'Fiber Optic Realtime',
  },
  {
    id: 'seismo_ppn_padang',
    name: 'Sensor Seismometer Padang Panjang (PPN)',
    code: 'BMKG-PPN',
    family: 'SOLID_EARTH_SEISMIC',
    subCategory: 'Broadband Seismometer & Borehole Accelerometer',
    platform: 'BOREHOLE',
    provider: 'BMKG InaTEWS',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -0.4612,
    lng: 100.3951,
    altitudeM: 780,
    status: 'ONLINE',
    samplingRate: '100 Hz Realtime',
    primaryMeasurement: 'Getaran Sesar Semangko & Megathrust Mentawai',
    unit: 'gal',
    currentValue: '0.015 gal',
    accuracy: '±0.0002 gal',
    coverage: 'Sumatera Barat & Kepulauan Mentawai',
    disasterRelevance: ['GEMPA', 'TSUNAMI'],
    description: 'Instalasi borehole dalam di koridor Sesar Besar Sumatera (Sesar Semangko) memantau akumulasi regangan tektonik Mentawai Megathrust.',
    lastPing: 'Live Realtime (< 1s)',
    telemetryType: 'Satelit VSAT & Radio Link',
  },
  {
    id: 'seismo_palukoro_creep',
    name: 'Array Sensor Patahan Aktif Sesar Palu-Koro',
    code: 'PVMBG-PLK',
    family: 'SOLID_EARTH_SEISMIC',
    subCategory: 'Creepmeter & Strong-Motion Array',
    platform: 'GROUND_STATION',
    provider: 'PVMBG / BRIN',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -0.9015,
    lng: 119.8654,
    altitudeM: 110,
    status: 'ACTIVE',
    samplingRate: '10 Hz Kontinu',
    primaryMeasurement: 'Laju Geser Sesar Strike-Slip Horisontal',
    unit: 'mm/bulan',
    currentValue: '3.5 mm/bulan',
    accuracy: '±0.05 mm',
    coverage: 'Palu Graben & Teluk Palu',
    disasterRelevance: ['GEMPA', 'TEKTONIK', 'TSUNAMI'],
    description: 'Sensor creepmeter mikro dan akselerometer mendeteksi rayapan dan akumulasi regangan geser di sepanjang segmen Sesar Palu-Koro.',
    lastPing: '2 menit lalu',
    telemetryType: '4G LTE Telemetri',
  },
  {
    id: 'seismo_usgs_gsn_palau',
    name: 'USGS Global Seismographic Network Palau (PAL)',
    code: 'USGS-PALU',
    family: 'SOLID_EARTH_SEISMIC',
    subCategory: 'Deep Seismic Observatory',
    platform: 'GROUND_STATION',
    provider: 'USGS / IRIS',
    country: 'Internasional',
    flag: '🇺🇸',
    lat: 7.3374,
    lng: 134.4811,
    altitudeM: 40,
    status: 'ONLINE',
    samplingRate: '100 Hz Realtime',
    primaryMeasurement: 'Gelombang Seismik Teleseismik Global Pasifik Barat',
    unit: 'counts/s',
    currentValue: '124 counts/s',
    accuracy: 'Standar USGS Kelas A',
    coverage: 'Pasifik Barat & Indonesia Timur',
    disasterRelevance: ['GEMPA', 'TSUNAMI'],
    description: 'Stasiun jangkar jaringan seismik global USGS/IRIS untuk verifikasi penentuan episenter gempa subduksi lempeng Filipina dan laut Maluku.',
    lastPing: 'Live (< 2s)',
    telemetryType: 'Dedicated Internet Backbone',
  },

  // ================= 2. GEODESY, GNSS & GRAVITY =================
  {
    id: 'gnss_csby_surabaya',
    name: 'Stasiun InaCORS Geodetik Kontinu Surabaya (CSBY)',
    code: 'BIG-CSBY',
    family: 'GEODESY_GNSS_GRAVITY',
    subCategory: 'Continuous Operating Reference Station (CORS)',
    platform: 'GROUND_STATION',
    provider: 'Badan Informasi Geospasial (BIG)',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -7.2824,
    lng: 112.7951,
    altitudeM: 18,
    status: 'ONLINE',
    samplingRate: '1 Hz Kontinu',
    primaryMeasurement: 'Vektor Deformasi Tektonik 3D (dN, dE, dU)',
    unit: 'mm/tahun',
    currentValue: 'Vektor: 26.4 mm/thn Azimuth 108°',
    accuracy: '±1.2 mm horizontal, ±2.8 mm vertikal',
    coverage: 'Cekungan Jawa Timur & Selat Madura',
    disasterRelevance: ['TEKTONIK', 'GEMPA', 'SUBSIDENCE'],
    description: 'Stasiun GNSS referensi geodetik kontinu kelas I memantau pergerakan tektonik mikro Lempeng Sunda terhadap penunjaman busur selatan Jawa.',
    lastPing: 'Live Realtime (< 1s)',
    telemetryType: 'Fiber Optic Terestris',
  },
  {
    id: 'gnss_cyog_yogyakarta',
    name: 'Stasiun InaCORS Geodetik Yogyakarta (CYOG)',
    code: 'BIG-CYOG',
    family: 'GEODESY_GNSS_GRAVITY',
    subCategory: 'Continuous Operating Reference Station (CORS)',
    platform: 'GROUND_STATION',
    provider: 'Badan Informasi Geospasial (BIG)',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -7.7712,
    lng: 110.3778,
    altitudeM: 145,
    status: 'ONLINE',
    samplingRate: '1 Hz Kontinu',
    primaryMeasurement: 'Laju Deformasi Zona Sesar Opak & Subduksi',
    unit: 'mm/tahun',
    currentValue: 'Vektor: 28.1 mm/thn Azimuth 112°',
    accuracy: '±1.0 mm horizontal',
    coverage: 'D.I. Yogyakarta & Sesar Opak',
    disasterRelevance: ['TEKTONIK', 'GEMPA'],
    description: 'Pemantauan regangan geser elastis di sekitar Sesar Opak yang pernah memicu gempa dahsyat Yogyakarta 2006.',
    lastPing: 'Live Realtime (< 1s)',
    telemetryType: 'Fiber Optic & 4G Backup',
  },
  {
    id: 'gnss_grace_gravity',
    name: 'Satelit GRACE-FO Twin Gravimetry (Massa Air & Es)',
    code: 'NASA-GRACEFO',
    family: 'GEODESY_GNSS_GRAVITY',
    subCategory: 'Satellite Gravimetry Laser Ranging',
    platform: 'SATELLITE',
    provider: 'NASA JPL / GFZ Potsdam',
    country: 'Internasional',
    flag: '🇺🇸',
    lat: -2.5000,
    lng: 118.0000,
    altitudeM: 490000, // Orbit LEO ~490 km
    status: 'ONLINE',
    samplingRate: 'Revisit Orbit Bulanan',
    primaryMeasurement: 'Anomali Massa Gravitasi Setara Tebal Air (EWH)',
    unit: 'cm EWH',
    currentValue: '-3.2 cm EWH (Defisit Akuifer Musim Kemarau)',
    accuracy: 'Sensitivitas skala basin mikrogravitasi',
    coverage: 'Global & Seluruh Kepulauan Indonesia',
    disasterRelevance: ['KEKERINGAN', 'TEKTONIK', 'SUBSIDENCE'],
    description: 'Dua satelit kembar mengukur fluktuasi gravitasi mikro bumi untuk memetakan penipisan air tanah dalam dan perubahan massa litosfer.',
    lastPing: 'Data Sinkronisasi Orbit Harian',
    telemetryType: 'Ka-Band & Optical Laser Inter-satellite Ranging',
  },

  // ================= 3. VOLCANO =================
  {
    id: 'volc_merapi_babadan',
    name: 'Pos Pengamatan Gunung Merapi Babadan (PVM-MRB)',
    code: 'PVMBG-MRB',
    family: 'VOLCANO',
    subCategory: 'Multi-Parameter Volcano Observatory',
    platform: 'GROUND_STATION',
    provider: 'PVMBG BPPTKG',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -7.5412,
    lng: 110.4285,
    altitudeM: 1275,
    status: 'ALERT',
    samplingRate: '50 Hz Seismik, 10 menit Gas/Tilt',
    primaryMeasurement: 'Seismisitas Magma, Fluks SO2, & Deformasi Tilt',
    unit: 'µrad / ton/hari',
    currentValue: 'Tilt: +12.4 µrad (Inflasi Puncak), SO2: 480 ton/hari',
    accuracy: 'Tilt: ±0.01 µrad, SO2: ±15 ton/hari',
    coverage: 'Sektor Barat Laut Gunung Merapi',
    disasterRelevance: ['GUNUNG_API', 'LONGSOR'],
    description: 'Stasiun terpadu garda terdepan BPPTKG memantau pertumbuhan kubah lava, guguran awan panas, dan inflasi kantung magma Merapi.',
    lastPing: 'Live Realtime (< 1s)',
    telemetryType: 'Radio Link Digital & Fiber Optic',
  },
  {
    id: 'volc_semeru_sawur',
    name: 'Pos Pengamatan Gunung Semeru Gunung Sawur',
    code: 'PVMBG-SMR',
    family: 'VOLCANO',
    subCategory: 'Seismometer Vulkanik & Sensor Aliran Lahar',
    platform: 'GROUND_STATION',
    provider: 'PVMBG Magma',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -8.1812,
    lng: 112.9814,
    altitudeM: 750,
    status: 'ALERT',
    samplingRate: 'Realtime Kontinu',
    primaryMeasurement: 'Seismik Gempa Erupsi & Sensor Getaran Lahar (AFM)',
    unit: 'Amplitudo (mm) / Frekuensi',
    currentValue: 'Amplitudo Tremor: 22 mm, Erupsi: 18x/24jam',
    accuracy: 'Sensitivitas Tinggi',
    coverage: 'Lembah Besuk Kobokan & Curah Kobokan Lumajang',
    disasterRelevance: ['GUNUNG_API', 'BANJIR'],
    description: 'Mendeteksi letusan vertikal kawah Jonggring Saloko serta getaran akustik aliran banjir lahar dingin hujan di hulu sungai.',
    lastPing: 'Live Realtime (< 2s)',
    telemetryType: 'Radio Telemetri VHF & Satelit',
  },
  {
    id: 'volc_krakatau_selat_sunda',
    name: 'Stasiun Multi-Sensor Gunung Anak Krakatau',
    code: 'PVMBG-GAK',
    family: 'VOLCANO',
    subCategory: 'Seismometer Pulau, Kamera Termal & CCTV',
    platform: 'GROUND_STATION',
    provider: 'PVMBG / BMKG',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -6.1021,
    lng: 105.4231,
    altitudeM: 155,
    status: 'ACTIVE',
    samplingRate: '100 Hz Seismik, 5 fps Termal',
    primaryMeasurement: 'Letupan Strombolian & Termal Kawah Letusan',
    unit: '°C / Amplitudo',
    currentValue: 'Suhu Kawah: 340°C, Gempa Letusan: 8x/hari',
    accuracy: 'Sensor Termal ±1.5°C',
    coverage: 'Selat Sunda (Banten & Lampung)',
    disasterRelevance: ['GUNUNG_API', 'TSUNAMI'],
    description: 'Stasiun pulau pulau terluar Selat Sunda memantau ancaman erupsi freatomagmatik dan risiko tsunami runtuhan lereng pulau (flank collapse).',
    lastPing: 'Live (< 3s)',
    telemetryType: 'VSAT Solar-Powered Autonomous',
  },

  // ================= 4. OCEAN & TSUNAMI =================
  {
    id: 'tsunami_snet_tohoku',
    name: 'S-net Ocean Bottom Cabled Tsunami Network (S1N01)',
    code: 'NIED-S1N01',
    family: 'OCEAN_HYDROLOGY',
    subCategory: 'Seafloor Cable Tsunameter & OBS',
    platform: 'SEAFLOOR_CABLE',
    provider: 'NIED Japan',
    country: 'Jepang',
    flag: '🇯🇵',
    lat: 40.5210,
    lng: 143.8200,
    depthM: 4200,
    status: 'ONLINE',
    samplingRate: '100 Hz Seismik, 10 Hz Tekanan',
    primaryMeasurement: 'Tekanan Hidrostatis Kolom Air Laut & Gelombang OBS',
    unit: 'MPa / Tekanan Air',
    currentValue: '42.15 MPa (+0.02 m)',
    accuracy: 'Resolusi 1 mm kenaikan muka air laut',
    coverage: 'Palung Jepang (Japan Trench)',
    disasterRelevance: ['TSUNAMI', 'GEMPA'],
    description: 'Kabel serat optik bawah laut bertenaga kontinu memonitor gelombang tsunami 15-20 menit sebelum mencapai garis pantai timur Jepang.',
    lastPing: 'Live (< 1s)',
    telemetryType: 'Submarine Optical Fiber Backbone',
  },
  {
    id: 'tsunami_donet_nankai',
    name: 'DONET Seafloor Cabled Observatory (MDA01)',
    code: 'JAMSTEC-MDA01',
    family: 'OCEAN_HYDROLOGY',
    subCategory: 'High-Precision Seafloor Cable Node',
    platform: 'SEAFLOOR_CABLE',
    provider: 'JAMSTEC Japan',
    country: 'Jepang',
    flag: '🇯🇵',
    lat: 33.7210,
    lng: 136.5400,
    depthM: 2050,
    status: 'ONLINE',
    samplingRate: '100 Hz Seismik, 10 Hz Tekanan',
    primaryMeasurement: 'Tekanan Kuarsa Bourdon & Akselerometer Tiga-Aksis',
    unit: 'MPa',
    currentValue: '20.58 MPa (Normal)',
    accuracy: 'Deteksi anomali 0.5 cm',
    coverage: 'Palung Nankai (Nankai Trough Megathrust)',
    disasterRelevance: ['TSUNAMI', 'GEMPA', 'TEKTONIK'],
    description: 'Jaringan kabel bawah laut JAMSTEC untuk deteksi dini gempa megathrust Nankai dan tsunami terekam di dasar laut secara seketika.',
    lastPing: 'Live (< 1s)',
    telemetryType: 'Kabel Optik Dasar Laut',
  },
  {
    id: 'tsunami_dart_23401',
    name: 'NOAA DART-II Deep-Ocean Tsunami Buoy (Station 23401)',
    code: 'NOAA-23401',
    family: 'OCEAN_HYDROLOGY',
    subCategory: 'Deep Ocean Bottom Pressure Recorder (BPR) & Moored Buoy',
    platform: 'OCEAN_BUOY',
    provider: 'NOAA / NDBC',
    country: 'Amerika Serikat',
    flag: '🇺🇸',
    lat: 8.9240,
    lng: 88.5410,
    depthM: 3200,
    status: 'ONLINE',
    samplingRate: '15 detik (Mode Standar), 1 detik (Trigger Alert)',
    primaryMeasurement: 'Tekanan Dasar Laut (BPR Tsunameter)',
    unit: 'psia / Meter Muka Air',
    currentValue: '4682.4 psia (+0.01 m)',
    accuracy: 'Akurasi 1 milimeter kolom air laut',
    coverage: 'Samudra Hindia Timur & Teluk Benggala',
    disasterRelevance: ['TSUNAMI', 'GEMPA'],
    description: 'Pelampung laut dalam terhubung akustik dengan recorder dasar laut memantau perambatan gelombang tsunami di Samudra Hindia.',
    lastPing: 'Live (< 30s)',
    telemetryType: 'Akustik Bawah Air & Satelit Iridium',
  },
  {
    id: 'tsunami_tide_perak',
    name: 'Stasiun Pasang Surut Pelabuhan Tanjung Perak',
    code: 'BIG-PRK01',
    family: 'OCEAN_HYDROLOGY',
    subCategory: 'Acoustic & Radar Tide Gauge',
    platform: 'GROUND_STATION',
    provider: 'Badan Informasi Geospasial (BIG)',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -7.1952,
    lng: 112.7381,
    altitudeM: 2,
    status: 'ONLINE',
    samplingRate: '1 menit Kontinu',
    primaryMeasurement: 'Ketinggian Muka Air Laut Pasut Realtime',
    unit: 'meter',
    currentValue: '1.42 m (Pasang Purnama)',
    accuracy: '±0.5 cm',
    coverage: 'Selat Madura & Pesisir Surabaya',
    disasterRelevance: ['TSUNAMI', 'BANJIR'],
    description: 'Stasiun pasut permanen mencatat pasang surut air laut astronomis, rob pesisir, serta anomali gelombang tsunami garis pantai.',
    lastPing: 'Live Realtime (< 10s)',
    telemetryType: '4G VPN & Satelit Backup',
  },
  {
    id: 'hydro_bengawansolo_gauge',
    name: 'Radar Pengukur Level Sungai Bengawan Solo Bojonegoro',
    code: 'BBWS-BS04',
    family: 'OCEAN_HYDROLOGY',
    subCategory: 'Radar Water-Level & Discharge Sensor',
    platform: 'GROUND_STATION',
    provider: 'KemenPUPR BBWS Bengawan Solo',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -7.1512,
    lng: 111.8814,
    altitudeM: 28,
    status: 'ONLINE',
    samplingRate: '5 menit',
    primaryMeasurement: 'Tinggi Muka Air (TMA) & Estimasi Debit Aliran',
    unit: 'meter / m³/s',
    currentValue: 'TMA: 12.8 m (Status: Siaga Hijau)',
    accuracy: '±2 mm',
    coverage: 'DAS Bengawan Solo Hilir',
    disasterRelevance: ['BANJIR'],
    description: 'Sensor gelombang mikro non-kontak terpasang di bawah jembatan mengukur tinggi permukaan air sungai besar untuk mitigasi banjir luapan.',
    lastPing: 'Live (3 menit lalu)',
    telemetryType: 'Cellular IoT Telemetry',
  },

  // ================= 5. WEATHER & ATMOSPHERE =================
  {
    id: 'radar_sub_juanda',
    name: 'Radar Cuaca Doppler BMKG Juanda Surabaya (SUB)',
    code: 'BMKG-WRAD-SUB',
    family: 'WEATHER',
    subCategory: 'C-Band Dual-Polarization Weather Radar',
    platform: 'GROUND_STATION',
    provider: 'BMKG',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -7.3798,
    lng: 112.7874,
    altitudeM: 14,
    status: 'ONLINE',
    samplingRate: 'Scan Volume 10 menit',
    primaryMeasurement: 'Reflektivitas (dBZ), Kecepatan Radial & Klasifikasi Presipitasi',
    unit: 'dBZ / mm/jam',
    currentValue: 'Max Refl: 44 dBZ (Awan Konvektif Selat Madura)',
    accuracy: 'Deteksi butiran hidrometeor hingga radius 250 km',
    coverage: 'Radius 250 km (Gerbangkertosusila & Selat Madura)',
    disasterRelevance: ['CUACA_EKSTREM', 'BANJIR', 'LONGSOR'],
    description: 'Radar cuaca canggih dual-polarisasi memantau awan badai Cumulonimbus, angin puting beliung, dan intensitas curah hujan ekstrem di Jawa Timur.',
    lastPing: 'Scan terkini: 4 menit lalu',
    telemetryType: 'High-speed Fiber Optic Dedicated Network',
  },
  {
    id: 'radiosonde_cengkareng',
    name: 'Stasiun Pengamatan Udara Atas Radiosonde Cengkareng',
    code: 'BMKG-UA-CKG',
    family: 'ATMOSPHERE',
    subCategory: 'Upper-Air Sounding Radiosonde Balloon',
    platform: 'GROUND_STATION',
    provider: 'BMKG',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -6.1256,
    lng: 106.6558,
    altitudeM: 10,
    status: 'ONLINE',
    samplingRate: 'Peluncuran 2x Sehari (00Z & 12Z UTC)',
    primaryMeasurement: 'Profil Vertikal Atmosfer (0 - 30.000 meter)',
    unit: '°C / hPa / knot',
    currentValue: 'Tropopause: 16.800 m (-82.4°C), CAPE: 2450 J/kg',
    accuracy: 'Sensor WMO Certified',
    coverage: 'Vertikal Seluruh Jabodetabek & Selat Sunda',
    disasterRelevance: ['CUACA_EKSTREM', 'BANJIR'],
    description: 'Balon radiosonde pembawa sensor GNSS, termistor, dan higrometer menembus atmosfer hingga 30 km untuk mengukur stabilitas udara konvektif.',
    lastPing: 'Data Sounding 00Z Valid',
    telemetryType: 'UHF Radio Telemetry 403 MHz',
  },

  // ================= 6. LAND & TERRAIN =================
  {
    id: 'landslide_cianjur_inclinometer',
    name: 'Array Monitoring Longsor & Piezometer Cianjur',
    code: 'PVMBG-LEWS-CJR',
    family: 'LAND_TERRAIN',
    subCategory: 'Borehole Inclinometer & Soil Moisture Array',
    platform: 'BOREHOLE',
    provider: 'PVMBG / UGM LEWS',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -6.8241,
    lng: 107.1354,
    altitudeM: 520,
    status: 'ACTIVE',
    samplingRate: '15 menit',
    primaryMeasurement: 'Pergeseran Lapisan Tanah Bawah & Tekanan Pori',
    unit: 'mm pergeseran / kPa',
    currentValue: 'Displacement: 1.4 mm, Pori: 14.2 kPa (Stabil)',
    accuracy: '±0.02 mm deviasi kemiringan',
    coverage: 'Lereng Rawan Sesar Cugenang - Cianjur',
    disasterRelevance: ['LONGSOR', 'GEMPA'],
    description: 'Pipa inklinometer dan piezometer air pori dipasang menembus bidang gelincir tanah pasca-gempa Cianjur untuk mendeteksi rayapan longsor susulan.',
    lastPing: 'Live (8 menit lalu)',
    telemetryType: 'LoRaWAN Gateway to 4G',
  },

  // ================= 7. REMOTE SENSING SATELLITES =================
  {
    id: 'sat_sentinel1_sar',
    name: 'Satelit Radar Sentinel-1 SAR (InSAR Deformasi)',
    code: 'ESA-S1-CSAR',
    family: 'REMOTE_SENSING',
    subCategory: 'C-Band Synthetic Aperture Radar (SAR)',
    platform: 'SATELLITE',
    provider: 'ESA Copernicus',
    country: 'Eropa',
    flag: '🇪🇺',
    lat: -7.0000,
    lng: 110.0000,
    altitudeM: 693000, // Orbit LEO ~693 km
    status: 'ONLINE',
    samplingRate: 'Siklus Ulang Orbit 6-12 Hari',
    primaryMeasurement: 'Interferometri Fase Radar (InSAR) Deformasi Kerak Bumi',
    unit: 'mm/tahun deformasi',
    currentValue: 'Deteksi amblesan tanah Semarang & Jakarta (-8.4 cm/thn)',
    accuracy: 'Ketelitian hingga skala milimeter pada garis pandang LOS',
    coverage: 'Swath 250 km (Mode Interferometric Wide IW)',
    disasterRelevance: ['TEKTONIK', 'GEMPA', 'BANJIR', 'GUNUNG_API', 'SUBSIDENCE'],
    description: 'Radar gelombang mikro tembus awan siang/malam; pasangan citra radar menghasilkan interferogram deformasi gempa dan laju amblesan tanah.',
    lastPing: 'Orbit Pass Terbaru Terproses',
    telemetryType: 'X-Band Downlink EDRS Laser Inter-Satellite',
  },
  {
    id: 'sat_sentinel2_msi',
    name: 'Satelit Optik Resolusi Tinggi Sentinel-2 (MSI)',
    code: 'ESA-S2-MSI',
    family: 'REMOTE_SENSING',
    subCategory: 'Multispectral Instrument (13 Kanal Spektra)',
    platform: 'SATELLITE',
    provider: 'ESA Copernicus',
    country: 'Eropa',
    flag: '🇪🇺',
    lat: -8.0000,
    lng: 115.0000,
    altitudeM: 786000,
    status: 'ONLINE',
    samplingRate: 'Revisit 5 Hari di Khatulistiwa',
    primaryMeasurement: 'Reflektansi Permukaan (VNIR, Red-Edge, SWIR)',
    unit: 'Nilai Reflektansi Spektral / Indeks Vegetasi',
    currentValue: 'NDVI Hijau Kanopi: 0.76 (Sehat)',
    accuracy: 'Resolusi spasial 10 m, 20 m, dan 60 m',
    coverage: 'Swath Lebar 290 km',
    disasterRelevance: ['BANJIR', 'KARHUTLA', 'LONGSOR', 'KEKERINGAN'],
    description: 'Pencitraan multispektral bumi untuk pemetaan genangan banjir, jejak luka bakar karhutla, dan indeks vegetasi kawasan hutan.',
    lastPing: 'Produk L2A BOA Reflektansi Tersedia',
    telemetryType: 'X-Band Downlink & Cloud Processing',
  },
  {
    id: 'sat_swot_hydrology',
    name: 'Satelit SWOT (Surface Water and Ocean Topography)',
    code: 'NASA-CNES-SWOT',
    family: 'REMOTE_SENSING',
    subCategory: 'Ka-Band Radar Interferometer (KaRIn)',
    platform: 'SATELLITE',
    provider: 'NASA JPL / CNES / CSA / UKSA',
    country: 'Internasional',
    flag: '🇺🇸',
    lat: -1.5000,
    lng: 114.0000,
    altitudeM: 890000,
    status: 'ONLINE',
    samplingRate: 'Siklus Ulang 21 Hari',
    primaryMeasurement: 'Elevasi 2D Permukaan Sungai Lebar >50m, Danau & Laut',
    unit: 'meter elevasi air',
    currentValue: 'Tinggi Air Sungai Mahakam: 8.42 m MSL',
    accuracy: 'Akurasi vertikal beberapa sentimeter untuk danau/sungai',
    coverage: 'Swath Ganda 120 km',
    disasterRelevance: ['BANJIR', 'OCEAN_HYDROLOGY' as any],
    description: 'Satelit revolusioner KaRIn mengukur tinggi air di jutaan danau, sungai besar, dan laut dunia secara komprehensif dari antariksa.',
    lastPing: 'Produk Level-2 Surface Water',
    telemetryType: 'Ka-Band High-Rate Telemetry',
  },
  {
    id: 'sat_himawari9_ahi',
    name: 'Satelit Geostasioner Himawari-9 (AHI)',
    code: 'JMA-HIMAWARI9',
    family: 'REMOTE_SENSING',
    subCategory: 'Advanced Himawari Imager (16 Kanal Spektra)',
    platform: 'SATELLITE',
    provider: 'Japan Meteorological Agency (JMA) / BMKG',
    country: 'Jepang',
    flag: '🇯🇵',
    lat: 0.0000,
    lng: 140.7000, // Posisi orbital geostasioner 140.7° BT
    altitudeM: 35786000, // Orbit Geostasioner ~35.786 km
    status: 'ONLINE',
    samplingRate: 'Penuh Cakupan Bumi Setiap 10 Menit',
    primaryMeasurement: 'Suhu Puncak Awan Inframerah & Deteksi Asap/Abu Vulkanik',
    unit: '°C (Brightness Temperature)',
    currentValue: 'Suhu Puncak Awan Konvektif Jawa: -78.2°C',
    accuracy: 'Resolusi 0.5 km (Visual) hingga 2 km (Inframerah)',
    coverage: 'Seluruh Benua Maritim Indonesia & Asia Pasifik',
    disasterRelevance: ['CUACA_EKSTREM', 'GUNUNG_API', 'KARHUTLA', 'BANJIR'],
    description: 'Satelit geostasioner utama BMKG memantau pembentukan awan badai tropis, pergerakan abu letusan gunung api, dan asap karhutla setiap 10 menit.',
    lastPing: 'Citra Realtime 10 Menit Terakhir',
    telemetryType: 'Direct Broadcast Geostasioner',
  },

  // ================= 8. BIOSPHERE & ENVIRONMENT =================
  {
    id: 'env_tropomi_s5p',
    name: 'Satelit TROPOMI Sentinel-5P (Kualitas Udara & Gas Vulkanik)',
    code: 'ESA-S5P-TROPOMI',
    family: 'BIOSPHERE_ENVIRONMENT',
    subCategory: 'Tropospheric Optical Absorption Spectrometer',
    platform: 'SATELLITE',
    provider: 'ESA / Royal Netherlands Meteorological Institute (KNMI)',
    country: 'Eropa',
    flag: '🇪🇺',
    lat: -6.2000,
    lng: 106.8000,
    altitudeM: 824000,
    status: 'ONLINE',
    samplingRate: 'Pencitraan Harian Global',
    primaryMeasurement: 'Total Kolom Troposfer Gas SO2, NO2, O3, CH4, & Karbon',
    unit: 'mol/m² / Dobson Units',
    currentValue: 'NO2 Jakarta: 14.2 µmol/m², SO2 Merapi: 0.8 DU',
    accuracy: 'Resolusi 5.5 x 3.5 km²',
    coverage: 'Global Harian',
    disasterRelevance: ['GUNUNG_API', 'KARHUTLA', 'CUACA_EKSTREM'],
    description: 'Instrumen spektroskopi atmosfer paling sensitif mendeteksi kepulan sulfur dioksida gunung api aktif dan polusi nitrogen dioksida perkotaan.',
    lastPing: 'Produk L2 Harian Tersedia',
    telemetryType: 'X-Band Downlink Svalbard',
  },

  // ================= 9. HUMAN INFRASTRUCTURE =================
  {
    id: 'infra_suramadu_shms',
    name: 'Sensor Kesehatan Struktur Jembatan Suramadu (SHMS)',
    code: 'PUPR-SURAMADU-SHM',
    family: 'HUMAN_INFRASTRUCTURE',
    subCategory: 'Triaxial Accelerometer & Strain Gauge',
    platform: 'INFRASTRUCTURE_MOUNTED',
    provider: 'KemenPUPR Bina Marga',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -7.1812,
    lng: 112.7754,
    altitudeM: 35,
    status: 'ONLINE',
    samplingRate: '100 Hz Kontinu',
    primaryMeasurement: 'Frekuensi Resonansi Getaran Gelagar & Tegangan Kabel',
    unit: 'Hz / Microstrain (µε)',
    currentValue: 'Frekuensi Utama: 0.38 Hz, Tegangan: 120 µε (Aman)',
    accuracy: 'Deteksi perubahan getaran fraksi mikrogravitasi',
    coverage: 'Bentang Utama Jembatan Kabel Pancang 818 meter',
    disasterRelevance: ['GEMPA', 'CUACA_EKSTREM'],
    description: 'Jaringan 48 sensor akselerometer, strain gauge, dan anemometer angin terpasang pada pilon jembatan untuk mendeteksi respons saat gempa bumi.',
    lastPing: 'Live Realtime (< 1s)',
    telemetryType: 'Kabel Serat Optik Jembatan Internal',
  },
  {
    id: 'infra_jatiluhur_dam',
    name: 'Sensor Rembesan & Piezometer Bendungan Ir. H. Djuanda (Jatiluhur)',
    code: 'PJT2-JTL01',
    family: 'HUMAN_INFRASTRUCTURE',
    subCategory: 'Piezometer Vibrating Wire & Inclinometer Tubuh Bendungan',
    platform: 'INFRASTRUCTURE_MOUNTED',
    provider: 'Perum Jasa Tirta II',
    country: 'Indonesia',
    flag: '🇮🇩',
    lat: -6.5254,
    lng: 107.3874,
    altitudeM: 107,
    status: 'ONLINE',
    samplingRate: '1 jam',
    primaryMeasurement: 'Tekanan Pori Inti Tanah Liat & Debit Rembesan',
    unit: 'bar / Liter per menit',
    currentValue: 'Tekanan Pori: 4.2 bar, Rembesan: 8.4 L/menit (Normal)',
    accuracy: '±0.01 bar',
    coverage: 'Tubuh Bendungan Utama Waduk Terbesar Indonesia',
    disasterRelevance: ['BANJIR', 'GEMPA'],
    description: 'Sistem pemantauan integritas bendungan mengawasi tekanan pori di dalam inti bendungan dan rembesan air guna mencegah keruntuhan bendungan bencana.',
    lastPing: 'Live (15 menit lalu)',
    telemetryType: 'SCADA Telemetry Industrial',
  }
];

// Helper Functions
export function getAllEarthSensors(): EarthSensorNode[] {
  return GLOBAL_EARTH_SENSOR_NETWORK;
}

export function getSensorsByFamily(family: SensorFamily): EarthSensorNode[] {
  return GLOBAL_EARTH_SENSOR_NETWORK.filter((s) => s.family === family);
}

export function getSensorsByDisaster(disaster: DisasterCategory): EarthSensorNode[] {
  return GLOBAL_EARTH_SENSOR_NETWORK.filter((s) => s.disasterRelevance.includes(disaster));
}

export function getMasterTaxonomy(): MasterTaxonomyCategory[] {
  return MASTER_SENSOR_TAXONOMY;
}

export function getSensorRegistryStats() {
  const total = GLOBAL_EARTH_SENSOR_NETWORK.length;
  const online = GLOBAL_EARTH_SENSOR_NETWORK.filter((s) => s.status === 'ONLINE' || s.status === 'ACTIVE').length;
  const alert = GLOBAL_EARTH_SENSOR_NETWORK.filter((s) => s.status === 'ALERT').length;

  const countByFamily = GLOBAL_EARTH_SENSOR_NETWORK.reduce((acc, sensor) => {
    acc[sensor.family] = (acc[sensor.family] || 0) + 1;
    return acc;
  }, {} as Record<SensorFamily, number>);

  return {
    total,
    online,
    alert,
    countByFamily,
  };
}
