export type ChartCategory =
  | 'compare'
  | 'trend'
  | 'composition'
  | 'distribution'
  | 'relationship'
  | 'weather_scientific'
  | 'earthquake_seismic'
  | 'flow_hierarchy';

export interface ChartDefinition {
  id: string;
  name: string;
  category: ChartCategory;
  categoryName: string;
  icon: string;
  description: string;
  useCase: string;
  complexity: 'Dasar' | 'Menengah' | 'Lanjutan' | 'Spesialis Ilmiah';
  tags: string[];
}

export const CHART_CATEGORIES: Array<{ id: ChartCategory; name: string; icon: string; count: number }> = [
  { id: 'compare', name: 'Perbandingan (Comparison)', icon: '📊', count: 8 },
  { id: 'trend', name: 'Tren & Waktu (Time Series)', icon: '📈', count: 8 },
  { id: 'composition', name: 'Komposisi (Part-to-Whole)', icon: '🥧', count: 6 },
  { id: 'distribution', name: 'Distribusi & Statistik', icon: '📉', count: 5 },
  { id: 'relationship', name: 'Korelasi & Hubungan', icon: '🔗', count: 4 },
  { id: 'weather_scientific', name: 'Cuaca & Atmosfer (Meteo)', icon: '🌪️', count: 5 },
  { id: 'earthquake_seismic', name: 'Seismik & Kebumian', icon: '🌋', count: 4 },
  { id: 'flow_hierarchy', name: 'Aliran & Matriks (Flow/Heat)', icon: '🌊', count: 3 },
];

export const ALL_CHARTS: ChartDefinition[] = [
  // 1. Comparison
  {
    id: 'bar',
    name: 'Bar Chart (Kolom Vertikal)',
    category: 'compare',
    categoryName: 'Perbandingan',
    icon: '📊',
    description: 'Membandingkan nilai metrik tunggal antar kategori atau rentang waktu dengan panjang batang proporsional.',
    useCase: 'Perbandingan curah hujan per jam, suhu puncak antar kota, jumlah pos pemantau.',
    complexity: 'Dasar',
    tags: ['bar', 'kolom', 'perbandingan', 'kategori'],
  },
  {
    id: 'horizontal_bar',
    name: 'Horizontal Bar Chart',
    category: 'compare',
    categoryName: 'Perbandingan',
    icon: '📊',
    description: 'Menampilkan batang horizontal yang ideal untuk label teks panjang antar provinsi atau kabupaten.',
    useCase: 'Peringkat curah hujan tertinggi antar 38 provinsi, intensitas sambaran petir per wilayah.',
    complexity: 'Dasar',
    tags: ['horizontal', 'ranking', 'provinsi'],
  },
  {
    id: 'grouped_bar',
    name: 'Grouped Bar Chart (Kolom Berkelompok)',
    category: 'compare',
    categoryName: 'Perbandingan',
    icon: '📊',
    description: 'Membandingkan beberapa seri data (misal: suhu model ECMWF vs GFS vs BMKG) pada kategori yang sama.',
    useCase: 'Komparasi deviasi multi-model cuaca pada setiap stasiun meteorologi.',
    complexity: 'Menengah',
    tags: ['grouped', 'multi-model', 'komparasi'],
  },
  {
    id: 'stacked_bar',
    name: 'Stacked Bar Chart (Batang Bertumpuk)',
    category: 'compare',
    categoryName: 'Perbandingan',
    icon: '📊',
    description: 'Memperlihatkan total kumulatif sekaligus kontribusi masing-masing komponen pembentuknya.',
    useCase: 'Total kejadian bencana per bulan dipecah berdasarkan gempa, banjir, dan longsor.',
    complexity: 'Menengah',
    tags: ['stacked', 'akumulasi', 'segmen'],
  },
  {
    id: 'percent_stacked',
    name: '100% Stacked Bar (Proporsi Persen)',
    category: 'compare',
    categoryName: 'Perbandingan',
    icon: '📊',
    description: 'Menampilkan persentase relatif setiap komponen dari total 100% untuk melihat pergeseran proporsi.',
    useCase: 'Proporsi tipe tutupan awan (tinggi, menengah, rendah) sepanjang hari.',
    complexity: 'Menengah',
    tags: ['100%', 'persen', 'rasio'],
  },
  {
    id: 'lollipop',
    name: 'Lollipop Chart',
    category: 'compare',
    categoryName: 'Perbandingan',
    icon: '🍭',
    description: 'Variasi minimalis dari bar chart menggunakan garis ramping berujung lingkaran untuk mengurangi beban tinta visual.',
    useCase: 'Perbandingan kecepatan hembusan angin ekstrem di 15 bandara.',
    complexity: 'Menengah',
    tags: ['lollipop', 'minimalis', 'ranking'],
  },
  {
    id: 'bullet',
    name: 'Bullet Chart (Target vs Realisasi)',
    category: 'compare',
    categoryName: 'Perbandingan',
    icon: '🎯',
    description: 'Membandingkan nilai aktual dengan ambang batas bahaya (threshold) dan rentang kualitatif (Aman, Waspada, Bahaya).',
    useCase: 'Ketinggian air bendungan terhadap ambang Siaga 1, 2, dan 3.',
    complexity: 'Lanjutan',
    tags: ['bullet', 'kpi', 'ambang', 'threshold'],
  },
  {
    id: 'radar',
    name: 'Radar / Spider Chart (Multivariabel)',
    category: 'compare',
    categoryName: 'Perbandingan',
    icon: '🕸️',
    description: 'Memetakan profil multivariabel dalam diagram jaring radial 360° untuk analisis kerentanan wilayah.',
    useCase: 'Indeks resiliensi bencana sekolah (Bahaya Seismik, Banjir, Akses Evakuasi, Fasilitas Medis).',
    complexity: 'Lanjutan',
    tags: ['radar', 'spider', 'multivariat', 'profil'],
  },

  // 2. Trend
  {
    id: 'line',
    name: 'Line Chart (Garis Waktu Tunggal)',
    category: 'trend',
    categoryName: 'Tren Waktu',
    icon: '📈',
    description: 'Grafik garis standar yang menghubungkan titik-titik data temporal untuk memperlihatkan arah tren naik/turun.',
    useCase: 'Tren fluktuasi temperatur 24 jam ke depan, tekanan permukaan atmosfer.',
    complexity: 'Dasar',
    tags: ['line', 'suhu', 'waktu', 'tren'],
  },
  {
    id: 'multi_line',
    name: 'Multi-Line Comparison (Multi-Garis)',
    category: 'trend',
    categoryName: 'Tren Waktu',
    icon: '📈',
    description: 'Menampilkan beberapa kurva garis sekaligus untuk membandingkan proyeksi multi-sumber.',
    useCase: 'Kurva prediksi suhu ECMWF, GFS, JMA, ICON dan konsensus terkalibrasi.',
    complexity: 'Menengah',
    tags: ['multi-line', 'ensemble', 'perbandingan'],
  },
  {
    id: 'step_line',
    name: 'Step Line Chart (Garis Bertingkat)',
    category: 'trend',
    categoryName: 'Tren Waktu',
    icon: '🪜',
    description: 'Kurva garis patah bertangga yang mempertahankan nilai konstan sampai terjadi perubahan terukur.',
    useCase: 'Status peringatan dini cuaca (Level 1 Hijau -> Level 2 Kuning -> Level 3 Merah).',
    complexity: 'Menengah',
    tags: ['step', 'tingkat', 'status'],
  },
  {
    id: 'area',
    name: 'Area Chart (Wilayah Bergradien)',
    category: 'trend',
    categoryName: 'Tren Waktu',
    icon: '📉',
    description: 'Mengisi ruang di bawah garis dengan gradien transparan untuk menekankan volume dan besaran nilai.',
    useCase: 'Volume kumulatif presipitasi hujan harian, intensitas partikulat polusi PM2.5.',
    complexity: 'Dasar',
    tags: ['area', 'gradien', 'volume'],
  },
  {
    id: 'stacked_area',
    name: 'Stacked Area Chart',
    category: 'trend',
    categoryName: 'Tren Waktu',
    icon: '📉',
    description: 'Tumpukan beberapa area kontinu yang memperlihatkan tren akumulasi total dan pergeseran komponen dari waktu ke waktu.',
    useCase: 'Total emisi gas rumah kaca harian (CO2, CH4, N2O).',
    complexity: 'Menengah',
    tags: ['stacked area', 'grk', 'emisi'],
  },
  {
    id: 'streamgraph',
    name: 'Streamgraph (Aliran Organik)',
    category: 'trend',
    categoryName: 'Tren Waktu',
    icon: '〰️',
    description: 'Bentuk variasi area chart yang berpusat di sekitar sumbu tengah melengkung organik.',
    useCase: 'Visualisasi dinamika sebaran spektral frekuensi gelombang seismik atau tutupan awan.',
    complexity: 'Lanjutan',
    tags: ['streamgraph', 'organik', 'spektral'],
  },
  {
    id: 'fan_chart',
    name: 'Fan Chart (Pita Ketidakpastian Probabilistik)',
    category: 'trend',
    categoryName: 'Tren Waktu',
    icon: '🪭',
    description: 'Grafik proyeksi masa depan dengan rentang pita probabilistik (50%, 75%, 95% Confidence Band) untuk memperlihatkan ketidakpastian ensemble.',
    useCase: 'Prakiraan lintasan siklon tropis, proyeksi anomali suhu jangka panjang, fluktuasi ENSO.',
    complexity: 'Spesialis Ilmiah',
    tags: ['fan', 'confidence', 'ketidakpastian', 'ensemble'],
  },
  {
    id: 'forecast',
    name: 'Forecast Horizon Chart',
    category: 'trend',
    categoryName: 'Tren Waktu',
    icon: '🔮',
    description: 'Memisahkan garis historis aktual masa lalu (garis solid) dengan proyeksi masa depan (garis putus-putus).',
    useCase: 'Verifikasi model NWP: suhu aktual vs prediksi 48 jam ke depan.',
    complexity: 'Lanjutan',
    tags: ['forecast', 'prediksi', 'horizon'],
  },

  // 3. Composition
  {
    id: 'donut',
    name: 'Donut Chart (Lingkaran Cincin)',
    category: 'composition',
    categoryName: 'Komposisi',
    icon: '🍩',
    description: 'Menampilkan proporsi bagian dari keseluruhan dengan ruang kosong di tengah untuk metrik ringkasan.',
    useCase: 'Komposisi jenis sambaran petir (CG-, CG+, Intra-Cloud IC).',
    complexity: 'Dasar',
    tags: ['donut', 'komposisi', 'persen'],
  },
  {
    id: 'pie',
    name: 'Pie Chart (Diagram Pai Klasik)',
    category: 'composition',
    categoryName: 'Komposisi',
    icon: '🥧',
    description: 'Membagi lingkaran menjadi juring proporsional untuk memvisualisasikan komposisi kategori terbatas (< 6 sektor).',
    useCase: 'Pembagian zona bahaya seismik wilayah (Rendah, Sedang, Tinggi).',
    complexity: 'Dasar',
    tags: ['pie', 'pai', 'juring'],
  },
  {
    id: 'treemap',
    name: 'Treemap (Hierarki Persegi Luas)',
    category: 'composition',
    categoryName: 'Komposisi',
    icon: '🔲',
    description: 'Menampilkan data hierarkis bersarang menggunakan persegi panjang berbobot luas proporsional.',
    useCase: 'Sebaran jumlah stasiun pemantau BMKG per pulau dan per provinsi.',
    complexity: 'Lanjutan',
    tags: ['treemap', 'hierarki', 'luas'],
  },
  {
    id: 'polar_rose',
    name: 'Nightingale Rose / Polar Area',
    category: 'composition',
    categoryName: 'Komposisi',
    icon: '🌹',
    description: 'Diagram polar di mana sudut sektor bernilai sama namun jari-jarinya merepresentasikan frekuensi/besaran.',
    useCase: 'Frekuensi kejadian gempa per bulan dalam satu siklus tahunan.',
    complexity: 'Lanjutan',
    tags: ['polar', 'nightingale', 'siklus'],
  },
  {
    id: 'waterfall',
    name: 'Waterfall Chart (Kenaikan / Penurunan)',
    category: 'composition',
    categoryName: 'Komposisi',
    icon: '🌊',
    description: 'Memvisualisasikan efek kumulatif dari nilai positif dan negatif berturut-turut terhadap saldo akhir.',
    useCase: 'Keseimbangan neraca air hidrologi (Inflow Hujan - Evapotranspirasi - Limpasan = Simpanan Air).',
    complexity: 'Lanjutan',
    tags: ['waterfall', 'neraca', 'hidrologi'],
  },
  {
    id: 'funnel',
    name: 'Funnel Chart (Piramida Corong)',
    category: 'composition',
    categoryName: 'Komposisi',
    icon: '⏳',
    description: 'Menampilkan reduksi progresif data pada setiap tahapan sistematis.',
    useCase: 'Penyaringan data peringatan dini: Deteksi Sensor -> Verifikasi AI -> Rilis Nowcast -> Notifikasi Warga.',
    complexity: 'Menengah',
    tags: ['funnel', 'corong', 'tahapan'],
  },

  // 4. Distribution & Statistics
  {
    id: 'histogram',
    name: 'Histogram Frekuensi',
    category: 'distribution',
    categoryName: 'Distribusi & Statistik',
    icon: '📊',
    description: 'Mengelompokkan data kontinu ke dalam interval kelas (bins) untuk melihat bentuk distribusi frekuensi.',
    useCase: 'Distribusi magnitudo gempa bumi Indonesia, distribusi ketebalan hujan.',
    complexity: 'Dasar',
    tags: ['histogram', 'frekuensi', 'sebaran'],
  },
  {
    id: 'boxplot',
    name: 'Box & Whisker Plot (Kuartil & Outlier)',
    category: 'distribution',
    categoryName: 'Distribusi & Statistik',
    icon: '📦',
    description: 'Menampilkan nilai minimum, Q1 (25%), median (50%), Q3 (75%), maksimum, dan anomali pencilan (outliers).',
    useCase: 'Sebaran statistik suhu bulanan dan variasi curah hujan dasarian.',
    complexity: 'Lanjutan',
    tags: ['boxplot', 'kuartil', 'outlier', 'statistik'],
  },
  {
    id: 'violin_density',
    name: 'Violin / Density Distribution Plot',
    category: 'distribution',
    categoryName: 'Distribusi & Statistik',
    icon: '🎻',
    description: 'Menggabungkan boxplot dengan estimasi kepadatan kernel (KDE) untuk memperlihatkan puncak multimodal.',
    useCase: 'Distribusi kedalaman hiposenter gempa bumi (gempa dangkal vs dalam).',
    complexity: 'Spesialis Ilmiah',
    tags: ['violin', 'density', 'kde'],
  },
  {
    id: 'ogive',
    name: 'Ogive (Kurva Kumulatif S)',
    category: 'distribution',
    categoryName: 'Distribusi & Statistik',
    icon: '📈',
    description: 'Kurva frekuensi kumulatif berbentuk huruf S untuk mengidentifikasi persentil ambang bahaya.',
    useCase: 'Probabilitas kumulatif curah hujan melampaui 50 mm/hari atau 100 mm/hari.',
    complexity: 'Lanjutan',
    tags: ['ogive', 'kumulatif', 'persentil'],
  },
  {
    id: 'pareto',
    name: 'Pareto Chart (Aturan 80/20)',
    category: 'distribution',
    categoryName: 'Distribusi & Statistik',
    icon: '📉',
    description: 'Kombinasi bar terurut menurun dengan garis persentase kumulatif untuk menemukan 20% penyebab utama.',
    useCase: 'Identifikasi daerah penghasil 80% laporan kerusakan akibat cuaca ekstrem.',
    complexity: 'Lanjutan',
    tags: ['pareto', '80/20', 'prioritas'],
  },

  // 5. Relationship & Correlation
  {
    id: 'scatter',
    name: 'Scatter Plot (Pencaran Titik XY)',
    category: 'relationship',
    categoryName: 'Korelasi & Hubungan',
    icon: '⁖',
    description: 'Memetakan pasangan dua variabel kuantitatif untuk melihat pola korelasi positif, negatif, atau acak.',
    useCase: 'Hubungan intensitas curah hujan (mm) vs debit limpasan sungai (m³/s).',
    complexity: 'Dasar',
    tags: ['scatter', 'titik', 'korelasi'],
  },
  {
    id: 'bubble',
    name: 'Bubble Chart (Pencaran Gelembung 3D)',
    category: 'relationship',
    categoryName: 'Korelasi & Hubungan',
    icon: '🫧',
    description: 'Scatter plot di mana setiap titik memiliki dimensi ketiga berupa radius ukuran gelembung.',
    useCase: 'X: Kecepatan Angin, Y: Curah Hujan, Radius: Radius Dampak Awan Cumulonimbus (Cb).',
    complexity: 'Menengah',
    tags: ['bubble', 'gelembung', 'multivariabel'],
  },
  {
    id: 'correlation_matrix',
    name: 'Correlation Heatmap Matrix',
    category: 'relationship',
    categoryName: 'Korelasi & Hubungan',
    icon: '🧮',
    description: 'Matriks warna yang menunjukkan koefisien korelasi Pearson antar beberapa parameter atmosfer.',
    useCase: 'Matriks korelasi antara Suhu, Kelembapan, Tekanan, PM2.5, dan Kecepatan Angin.',
    complexity: 'Lanjutan',
    tags: ['matrix', 'korelasi', 'pearson'],
  },
  {
    id: 'hexbin',
    name: 'Hexbin Density Plot',
    category: 'relationship',
    categoryName: 'Korelasi & Hubungan',
    icon: '🛑',
    description: 'Mengelompokkan ribuan titik scatter ke dalam grid heksagonal untuk menghindari penumpukan data (*overplotting*).',
    useCase: 'Kepadatan sebaran jutaan koordinat sambaran petir di pulau Jawa.',
    complexity: 'Spesialis Ilmiah',
    tags: ['hexbin', 'heksagonal', 'density'],
  },

  // 6. Weather & Meteorology
  {
    id: 'wind_rose',
    name: 'Wind Rose (Mawar Angin 16 Arah)',
    category: 'weather_scientific',
    categoryName: 'Cuaca & Atmosfer (Meteo)',
    icon: '🧭',
    description: 'Diagram polar meteorologis resmi yang menampilkan arah mata angin dominan, frekuensi waktu, dan kelas kecepatan.',
    useCase: 'Perencanaan arah landasan pacu bandara, pemantauan hembusan angin puting beliung.',
    complexity: 'Spesialis Ilmiah',
    tags: ['wind rose', 'mawar angin', 'arah angin', 'kecepatan'],
  },
  {
    id: 'meteogram',
    name: 'Meteogram Terpadu Multi-Sumbu',
    category: 'weather_scientific',
    categoryName: 'Cuaca & Atmosfer (Meteo)',
    icon: '📊',
    description: 'Visualisasi meteorologi komprehensif yang menumpuk profil suhu, presipitasi, tekanan isobar, dan angin dalam 1 linimasa.',
    useCase: 'Sintesis lengkap prakiraan cuaca operasional bandara dan pelabuhan maritim.',
    complexity: 'Spesialis Ilmiah',
    tags: ['meteogram', 'nwp', 'sintesis', 'operasional'],
  },
  {
    id: 'sounding',
    name: 'Atmospheric Sounding (Profil Vertikal)',
    category: 'weather_scientific',
    categoryName: 'Cuaca & Atmosfer (Meteo)',
    icon: '🎈',
    description: 'Profil vertikal atmosfer dari permukaan tanah hingga lapisan stratosfer (1000 hPa s.d. 100 hPa).',
    useCase: 'Evaluasi potensi ledakan awan Cumulonimbus (CAPE, Lifted Index, K-Index).',
    complexity: 'Spesialis Ilmiah',
    tags: ['sounding', 'skew-t', 'cape', 'atmosfer vertikal'],
  },
  {
    id: 'aqi_gauge',
    name: 'AQI Dial Speedometer Gauge',
    category: 'weather_scientific',
    categoryName: 'Cuaca & Atmosfer (Meteo)',
    icon: '🧭',
    description: 'Indikator dial speedometer melingkar dengan skala warna kualitas udara (Hijau, Kuning, Oranye, Merah, Ungu, Hitam).',
    useCase: 'Status kualitas udara PM2.5 real-time & tingkat risiko kesehatan publik.',
    complexity: 'Menengah',
    tags: ['gauge', 'speedometer', 'aqi', 'pm2.5'],
  },
  {
    id: 'wave_rose',
    name: 'Wave & Swell Rose (Gelombang Maritim)',
    category: 'weather_scientific',
    categoryName: 'Cuaca & Atmosfer (Meteo)',
    icon: '🌊',
    description: 'Distribusi arah datangnya gelombang laut signifikan (*significant wave height*) dan periode gelombang.',
    useCase: 'Keselamatan pelayaran kapal ferry, perahu nelayan, dan dermaga pelabuhan.',
    complexity: 'Spesialis Ilmiah',
    tags: ['wave rose', 'gelombang', 'maritim', 'swell'],
  },

  // 7. Earthquake & Seismic
  {
    id: 'seismograph',
    name: 'Seismogram (Bentuk Gelombang Seismik)',
    category: 'earthquake_seismic',
    categoryName: 'Seismik & Kebumian',
    icon: '📈',
    description: 'Rekaman osilasi percepatan getaran tanah yang memperlihatkan kedatangan P-Wave (Primer) dan S-Wave (Sekunder).',
    useCase: 'Identifikasi waktu tempuh gelombang gempa dan penentuan jarak episenter ke stasiun seismik.',
    complexity: 'Spesialis Ilmiah',
    tags: ['seismogram', 'p-wave', 's-wave', 'getaran'],
  },
  {
    id: 'depth_mag_scatter',
    name: 'Depth vs Magnitude Scatter Plot',
    category: 'earthquake_seismic',
    categoryName: 'Seismik & Kebumian',
    icon: '🌋',
    description: 'Plot pencaran kedalaman hiposenter (km) terhadap magnitudo gempa dengan pewarnaan zona subduksi.',
    useCase: 'Analisis zona Benioff lempeng tektonik Indo-Australia yang menyusup di bawah lempeng Eurasia.',
    complexity: 'Spesialis Ilmiah',
    tags: ['depth', 'magnitude', 'subduksi', 'hiposenter'],
  },
  {
    id: 'gutenberg_richter',
    name: 'Gutenberg-Richter Law (Kurva b-value)',
    category: 'earthquake_seismic',
    categoryName: 'Seismik & Kebumian',
    icon: '📉',
    description: 'Hubungan empiris frekuensi gempa terhadap magnitudo logaritmik (log N = a - bM) untuk menghitung bahaya seismik.',
    useCase: 'Kalkulasi nilai b-value untuk estimasi akumulasi stres tektonik pada sesar aktif.',
    complexity: 'Spesialis Ilmiah',
    tags: ['gutenberg-richter', 'b-value', 'seismik hazard'],
  },
  {
    id: 'isoseismal_curve',
    name: 'Isoseismal MMI Attenuation Curve',
    category: 'earthquake_seismic',
    categoryName: 'Seismik & Kebumian',
    icon: '📐',
    description: 'Kurva pelemahan intensitas guncangan tanah (Skala MMI) seiring bertambahnya jarak dari pusat gempa.',
    useCase: 'Prakiraan wilayah terdampak guncangan rusak (MMI VI-VIII) untuk pengerahan tim SAR.',
    complexity: 'Lanjutan',
    tags: ['mmi', 'isoseismal', 'atenuasi'],
  },

  // 8. Flow & Hierarchy
  {
    id: 'calendar_heatmap',
    name: 'Calendar Heatmap (Matriks Kalender)',
    category: 'flow_hierarchy',
    categoryName: 'Aliran & Matriks',
    icon: '📅',
    description: 'Grid matriks hari demi hari sepanjang tahun yang diwarnai menurut intensitas kejadian.',
    useCase: 'Pemantauan Hari Tanpa Hujan (HTH) dan frekuensi hari basah ekstrem dalam 365 hari.',
    complexity: 'Lanjutan',
    tags: ['calendar', 'heatmap', 'hth', 'hari'],
  },
  {
    id: 'sankey_flow',
    name: 'Sankey Flux Flow Diagram',
    category: 'flow_hierarchy',
    categoryName: 'Aliran & Matriks',
    icon: '🔀',
    description: 'Diagram pita aliran dengan lebar garis proporsional terhadap kuantitas transfer antar entitas.',
    useCase: 'Aliran logistik darurat bencana dari gudang pusat ke posko kabupaten dan desa terdampak.',
    complexity: 'Lanjutan',
    tags: ['sankey', 'aliran', 'logistik'],
  },
  {
    id: 'parallel_coords',
    name: 'Parallel Coordinates Multi-Variabel',
    category: 'flow_hierarchy',
    categoryName: 'Aliran & Matriks',
    icon: '📏',
    description: 'Menampilkan setiap variabel sebagai sumbu vertikal paralel dengan garis yang melintasi semua sumbu.',
    useCase: 'Mendeteksi klaster profil mikroklimat yang memicu terbentuknya kabut radiasi atau badai.',
    complexity: 'Spesialis Ilmiah',
    tags: ['parallel coordinates', 'multivariat', 'klaster'],
  },
];
